CREATE DATABASE IF NOT EXISTS itt440;

USE itt440;

CREATE TABLE IF NOT EXISTS itt440 (id INT AUTO_INCREMENT PRIMARY KEY, user VARCHAR(255) NOT NULL, points INT NOT NULL, datetime_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);