version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    build: ./mysql
    ports:
      - "3306:3306"
    restart: always
  
  python-server:
    container_name: python-server
    build: ./python-server
    depends_on:
      - mysql
    ports:
      - "5002:5002"
    restart: always

  python-client:
    container_name: python-client
    build: ./python-client
    depends_on:
      - python-server
    restart: always

  c-server:
    container_name: c-server
    build: ./c-server
    depends_on:
      - mysql
    ports:
      - "6002:6002"
    restart: always

  c-client:
    container_name: c-client
    build: ./c-client
    depends_on:
      - c-server
    restart: always


# DEBUG-CONTAINER FOR C-CLIENT
  # ubuntu-container:
  #     container_name: debug-ubuntu
  #     image: ubuntu:latest
  #     command: sleep infinity
  #     tty: true
  #     stdin_open: true
  #     restart: always