version: '3'
services:
  mysql:
    container_name: mysql
    build: ./mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.2
    ports:
      - "3306:3306"
    restart: always
  
  luqman-python-server:
    container_name: luqman-python-server
    build: ./luqman-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.3
    ports:
      - "5002:5002"
    restart: always

  luqman-python-client:
    container_name: luqman-python-client
    build: ./luqman-python-client
    depends_on:
      - luqman-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.4
    restart: always

  luqman-c-server:
    container_name: luqman-c-server
    build: ./luqman-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.5
    ports:
      - "6002:6002"
    restart: always

  luqman-c-client:
    container_name: luqman-c-client
    build: ./luqman-c-client
    depends_on:
      - luqman-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.6
    restart: always

  fakhirul-python-server:
    container_name: fakhirul-python-server
    build: ./fakhirul-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.8
    ports:
      - "8123:8123"
    restart: always

  fakhirul-python-client:
    container_name: fakhirul-python-client
    build: ./fakhirul-python-client
    depends_on:
      - fakhirul-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.9
    restart: always

  fakhirul-c-server:
    container_name: fakhirul-c-server
    build: ./fakhirul-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.10
    ports:
      - "6123:6123"
    restart: always

  fakhirul-c-client:
    container_name: fakhirul-c-client
    build: ./fakhirul-c-client
    depends_on:
      - fakhirul-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.11
    restart: always

  nabil-python-server:
    container_name: nabil-python-server
    build: ./nabil-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.13
    ports:
      - "8004:8004"
    restart: always

  nabil-python-client:
    container_name: nabil-python-client
    build: ./nabil-python-client
    depends_on:
      - nabil-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.14
    restart: always

  nabil-c-server:
    container_name: nabil-c-server
    build: ./nabil-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.15
    ports:
      - "6097:6097"
    restart: always

  nabil-c-client:
    container_name: nabil-c-client
    build: ./nabil-c-client
    depends_on:
      - nabil-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.16
    restart: always

  sholeh-python-server:
    container_name: sholeh-python-server
    build: ./sholeh-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.18
    ports:
      - "8002:8002"
    restart: always

  sholeh-python-client:
    container_name: sholeh-python-client
    build: ./sholeh-python-client
    depends_on:
      - sholeh-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.19
    restart: always

  sholeh-c-server:
    container_name: sholeh-c-server
    build: ./sholeh-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.20
    ports:
      - "9002:9002"
    restart: always

  sholeh-c-client:
    container_name: sholeh-c-client
    build: ./sholeh-c-client
    depends_on:
      - sholeh-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.21
    restart: always

  ira-python-server:
    container_name: ira-python-server
    build: ./ira-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.22
    ports:
      - "4002:4002"
    restart: always

  ira-python-client:
    container_name: ira-python-client
    build: ./ira-python-client
    depends_on:
      - ira-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.23
    restart: always

  ira-c-server:
    container_name: ira-c-server
    build: ./ira-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.24
    ports:
      - "2002:2002"
    restart: always

  ira-c-client:
    container_name: ira-c-client
    build: ./ira-c-client
    depends_on:
      - ira-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.25
    restart: always

  azam-python-server:
    container_name: azam-python-server
    build: ./azam-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.26
    ports:
      - "8321:8321"
    restart: always

  azam-python-client:
    container_name: azam-python-client
    build: ./azam-python-client
    depends_on:
      - azam-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.27
    restart: always

  azam-c-server:
    container_name: azam-c-server
    build: ./azam-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.28
    ports:
      - "7123:7123"
    restart: always

  azam-c-client:
    container_name: azam-c-client
    build: ./azam-c-client
    depends_on:
      - azam-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.29
    restart: always

networks:
  itt440:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

