version: '3'
services:
  mysql:
    container_name: mysql
    build: ./mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.2
    ports:
      - "3306:3306"
    restart: always
  
  luqman-python-server:
    container_name: luqman-python-server
    build: ./luqman-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.3
    ports:
      - "5002:5002"
    restart: always

  luqman-python-client:
    container_name: luqman-python-client
    build: ./luqman-python-client
    depends_on:
      - luqman-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.4
    restart: always

  luqman-c-server:
    container_name: luqman-c-server
    build: ./luqman-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.5
    ports:
      - "6002:6002"
    restart: always

  luqman-c-client:
    container_name: luqman-c-client
    build: ./luqman-c-client
    depends_on:
      - luqman-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.6
    restart: always

  ira-python-server:
    container_name: ira-python-server
    build: ./ira-python-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.22
    ports:
      - "4002:4002"
    restart: always

  ira-python-client:
    container_name: ira-python-client
    build: ./ira-python-client
    depends_on:
      - ira-python-server
    networks:
      itt440:
        ipv4_address: 172.16.238.23
    restart: always

  ira-c-server:
    container_name: ira-c-server
    build: ./ira-c-server
    depends_on:
      - mysql
    networks:
      itt440:
        ipv4_address: 172.16.238.24
    ports:
      - "2002:2002"
    restart: always

  ira-c-client:
    container_name: ira-c-client
    build: ./ira-c-client
    depends_on:
      - ira-c-server
    networks:
      itt440:
        ipv4_address: 172.16.238.25
    restart: always

networks:
  itt440:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

