version: '3'

services:
  mysql:
    image: mysql:latest
    build: ./mysql
    ports:
      - "3306:3306"
    restart: always
  
  python-server:
    build: ./python-server
    depends_on:
      - mysql
    ports:
      - "5002:5002"
    restart: always

  python-client:
    build: ./python-client
    depends_on:
      - python-server
    restart: always
    